// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG74DtD0Ytd72Uu6RdwqynJLwb2zmZrm4',
    appId: '1:96111238748:web:5f07649d88e4696c439099',
    messagingSenderId: '96111238748',
    projectId: 'routes-app-4fdfb',
    authDomain: 'routes-app-4fdfb.firebaseapp.com',
    storageBucket: 'routes-app-4fdfb.firebasestorage.app',
    measurementId: 'G-4B3R1YJEX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Kgdt42nZQyfTXtvbutdjT1VeED1Jw-o',
    appId: '1:96111238748:android:917074c1128c991a439099',
    messagingSenderId: '96111238748',
    projectId: 'routes-app-4fdfb',
    storageBucket: 'routes-app-4fdfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYWCHPq29YH0la1bQPPf51nQA_E2X5Vx8',
    appId: '1:96111238748:ios:d5e56dbb8b8b7da8439099',
    messagingSenderId: '96111238748',
    projectId: 'routes-app-4fdfb',
    storageBucket: 'routes-app-4fdfb.firebasestorage.app',
    iosBundleId: 'com.example.routesCalculated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYWCHPq29YH0la1bQPPf51nQA_E2X5Vx8',
    appId: '1:96111238748:ios:d5e56dbb8b8b7da8439099',
    messagingSenderId: '96111238748',
    projectId: 'routes-app-4fdfb',
    storageBucket: 'routes-app-4fdfb.firebasestorage.app',
    iosBundleId: 'com.example.routesCalculated',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG74DtD0Ytd72Uu6RdwqynJLwb2zmZrm4',
    appId: '1:96111238748:web:0d5eeb6eabe1eed0439099',
    messagingSenderId: '96111238748',
    projectId: 'routes-app-4fdfb',
    authDomain: 'routes-app-4fdfb.firebaseapp.com',
    storageBucket: 'routes-app-4fdfb.firebasestorage.app',
    measurementId: 'G-XHS49KV614',
  );
}
